### ISSUE TITLE
Offtopic

### ISSUE THREAD

**Issue by M3351AN** [Coslly/Rensen#3]
![c4baeb5292b047a1643c3a2e291ea6ed](https://github.com/user-attachments/assets/0bf1a742-3c9f-4733-a35d-ec13ef1b94f7)
![86b54987bfea5ad3de8fbefe1bc318f0](https://github.com/user-attachments/assets/08757dc1-37ce-447f-a9e2-b8592b04a100)
![d8d757281bbd5774c0400c16784e072c](https://github.com/user-attachments/assets/40822d26-3e1f-4b16-9e8e-b5fa91bd6a68)
![665a75902cef91cf3b256ca3c7cf1e87](https://github.com/user-attachments/assets/af312329-e8c1-488c-a68a-ba2292510b87)
![e90afc6b23bab8695167bc019965231e](https://github.com/user-attachments/assets/d5b70b9a-c614-42f1-9932-9a71971e03e4)

**Comment by Coslly** [comment]
不用管 外部调的再nb也比不上内部HOOK功能 CS2对我来说太失望了我才公开这个 让他们圈吧只要别挂我的名字就好
我真没想到这20几年前的GUI设计还有人喜欢哈哈
