### ISSUE TITLE
新版本绘制偏框了

### ISSUE THREAD

**Issue by Shaw75** [Coslly/Rensen#6]
绘制偏框了

**Comment by Coslly** [comment]
请提供版本号和屏幕截图

**Comment by Shaw75** [comment]
![QQ图片20240819172630](https://github.com/user-attachments/assets/d73d4b58-f947-426c-a988-3cc3d2e776e7)
版本：4.58
全屏和窗口化都偏，老版本没问题

**Comment by Coslly** [comment]
Windows设置->系统->屏幕->缩放与布局 设置的百分之几？

**Comment by Shaw75** [comment]
125%

**Comment by Shaw75** [comment]
设置成100%就没问题了，但是老版本125%也没问题

**Comment by Coslly** [comment]
你说的老版本版本号是多少

**Comment by Coslly** [comment]
已更新 你看看还有没有偏框？

**Comment by Shaw75** [comment]
没问题了，谢谢

**Comment by Coslly** [comment]
> 如何打開中文菜单
> 謝謝

请设置系统语言为简体中文

**Comment by AkumaQoo** [comment]
> > 如何打開中文菜單
> > 謝謝
> 
> 請設定係統語言為簡體中文

OK 感謝

**Comment by AkumaQoo** [comment]
官方更新了~期待更新~感謝

**Comment by AkumaQoo** [comment]
> 官方更新了~期待更新~謝謝

想問~如何開啟自動射擊~我試不出來~看影片操作也弄不成功~可否教一下設定~感謝
