### ISSUE TITLE
磁吸瞄准似乎不起作用

### ISSUE THREAD

**Issue by 27AAFF** [Coslly/Rensen#7]
（关闭只磁吸头线、修改范围和平滑度也试过了）
https://streamable.com/4fkjv2

**Comment by Coslly** [comment]
> （关闭只磁吸头线、修改范围和平滑度也试过了）
> https://streamable.com/4fkjv2

窗口模式(带有标题栏)下无法使用磁吸瞄准 我会在后续修复它

**Comment by Coslly** [comment]
已修复
