### ISSUE TITLE
自适应自瞄不能用

### ISSUE THREAD

**Issue by SheRecalled** [Coslly/Rensen#8]
自适应自瞄不能用，打开后瞄准人开枪，准星来回乱跳打不中人，不瞄准人就正常

**Comment by SheRecalled** [comment]
https://streamable.com/adc9eo    开了之后就乱跳，关了 就正常

**Comment by Coslly** [comment]
请调整适合自己的自瞄平滑度。（平滑度太低）

我将在30分钟之后关闭该问题，如有其他问题请在30分钟内回复。

**Comment by SheRecalled** [comment]
平滑度拉满了，稍等我重新录制一下

**Comment by SheRecalled** [comment]
https://streamable.com/d6qesg

**Comment by Coslly** [comment]
> https://streamable.com/d6qesg

配置发过来

**Comment by SheRecalled** [comment]
> > https://streamable.com/d6qesg
> 
> 配置发过来

![微信图片_20240903192637](https://github.com/user-attachments/assets/e2492252-a991-4c5f-a9d2-4a3386d95e2b)

**Comment by Coslly** [comment]
> > > https://streamable.com/d6qesg
> > 
> > 
> > 配置发过来
> 
> ![微信图片_20240903192637](https://private-user-images.githubusercontent.com/180264358/363963087-e2492252-a991-4c5f-a9d2-4a3386d95e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjMxNjgsIm5iZiI6MTcyNTM2Mjg2OCwicGF0aCI6Ii8xODAyNjQzNTgvMzYzOTYzMDg3LWUyNDkyMjUyLWE5OTEtNGM1Zi1hOWQyLTRhMzM4NmQ5NWUyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMTI3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWYxYWU2ZTk3NTEzZDUzZjkzODI0NThiNzE0YTIyNDI3OTI5NDgyYzRhMDZhZTdhNDA3NTUzZGRkNjcyYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B2wqXQ9jWrEQna22BjhR2iaRc1J4QGGbP_CD2EDhX1E)

**菜单参数** **_字符串_**复制粘贴发过来 ：）

**Comment by SheRecalled** [comment]
> > https://streamable.com/d6qesg
> 
> 配置发过来

8.21版本之前还能用，在之后的更新就都不能用了

**Comment by Coslly** [comment]
> > > > https://streamable.com/d6qesg
> > > 
> > > 
> > > 配置发过来
> > 
> > 
> > ![微信图片_20240903192637](https://private-user-images.githubusercontent.com/180264358/363963087-e2492252-a991-4c5f-a9d2-4a3386d95e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjMxNjgsIm5iZiI6MTcyNTM2Mjg2OCwicGF0aCI6Ii8xODAyNjQzNTgvMzYzOTYzMDg3LWUyNDkyMjUyLWE5OTEtNGM1Zi1hOWQyLTRhMzM4NmQ5NWUyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMTI3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWYxYWU2ZTk3NTEzZDUzZjkzODI0NThiNzE0YTIyNDI3OTI5NDgyYzRhMDZhZTdhNDA3NTUzZGRkNjcyYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B2wqXQ9jWrEQna22BjhR2iaRc1J4QGGbP_CD2EDhX1E)
> 
> **菜单参数** **_字符串_**复制粘贴发过来 ：）

打开同目录Rensen.cfg文件 复制里面的所有内容 粘贴发送

**Comment by SheRecalled** [comment]
> > > > > https://streamable.com/d6qesg
> > > > 
> > > > 
> > > > 配置发过来
> > > 
> > > 
> > > ![微信图片_20240903192637](https://private-user-images.githubusercontent.com/180264358/363963087-e2492252-a991-4c5f-a9d2-4a3386d95e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjMxNjgsIm5iZiI6MTcyNTM2Mjg2OCwicGF0aCI6Ii8xODAyNjQzNTgvMzYzOTYzMDg3LWUyNDkyMjUyLWE5OTEtNGM1Zi1hOWQyLTRhMzM4NmQ5NWUyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMTI3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWYxYWU2ZTk3NTEzZDUzZjkzODI0NThiNzE0YTIyNDI3OTI5NDgyYzRhMDZhZTdhNDA3NTUzZGRkNjcyYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B2wqXQ9jWrEQna22BjhR2iaRc1J4QGGbP_CD2EDhX1E)
> > 
> > 
> > **菜单参数** **_字符串_**复制粘贴发过来 ：）
> 
> 打开同目录Rensen.cfg文件 复制里面的所有内容 粘贴发送


500
1
1
4
1
3
1
10
100
1
1
0
1
1
50
1
6
0
5
1
5
0
1

13
0
1
9
1
255
0
100
0
400
40
250
40
0
50
0

**Comment by SheRecalled** [comment]
1
6
1
1
0
1
1
100
1
1
0
100
0
0
100
0
1
100
5
1
5
0
1
150
1
0.015
0.004
1
1
2
1
500
1
0
0
1
1
0
1
0
1
1
1
1
40
80
0
255
255
255
255
1
1
1
4
260
180
26
11
1
1
1000
10
1
1
5
5
1
1
0
0
1
1
1
0
0
1
160
800
350
0
45
0
200
200
255
250
200
200
255
2
0
1
1
4
10
10
0
1
2
10
1
500
1
1
4
1
3
1
10
100
1
1
0
1
1
50
1
6
0
5
1
5
0
1

13
0
1
9
1
255
0
100
0
400
40
250
40
0
50
0

**Comment by Coslly** [comment]
> 1 6 1 1 0 1 1 100 1 1 0 100 0 0 100 0 1 100 5 1 5 0 1 150 1 0.015 0.004 1 1 2 1 500 1 0 0 1 1 0 1 0 1 1 1 1 40 80 0 255 255 255 255 1 1 1 4 260 180 26 11 1 1 1000 10 1 1 5 5 1 1 0 0 1 1 1 0 0 1 160 800 350 0 45 0 200 200 255 250 200 200 255 2 0 1 1 4 10 10 0 1 2 10 1 500 1 1 4 1 3 1 10 100 1 1 0 1 1 50 1 6 0 5 1 5 0 1
> 
> 13 0 1 9 1 255 0 100 0 400 40 250 40 0 50 0

请更新最新版本

**Comment by SheRecalled** [comment]
是这个菜单参数更新吗？   辅助已经是最新版本了
